import express from 'express';
import { getPublicarViaje,createPublicarViaje,updatePublicarViaje,deletePublicarViaje, getViajesFilter,getViajeUser} from '../controller/PublicarViajeController.js';
import  {verifyToken}  from '../middleware/auth.js';
const rotuer = express.Router();
rotuer.get('/publicar',verifyToken, getPublicarViaje);
rotuer.post('/publicar', verifyToken,createPublicarViaje);
rotuer.put('/publicar/:id', verifyToken,updatePublicarViaje);
rotuer.delete('/publicar/:id',verifyToken,deletePublicarViaje);
rotuer.post('/publicar/filter',verifyToken,getViajesFilter);
rotuer.get('/publicado/viaje',verifyToken,getViajeUser);
export default rotuer;
